language: node_js

node_js:
    - stable

sudo: false

install:
    - npm install

script:
    - npm run lint
    - npm run cover

after_script:
    - npm run coveralls

cache:
    directories:
        - node_modules

notifications:
    email: false
