language: node_js

node_js:
    - stable

sudo: false

install:
    - yarn

script:
    - yarn lint
    - yarn cover

after_script:
    - yarn coveralls

cache:
    yarn: true
    directories:
        - node_modules

notifications:
    email: false
